#
#mybatis-plus:
#  configuration:
#    map‐underscore‐to‐camel‐case: true
#
#spring:
#  application:
#    name: springboot-case-demo
#  #datasource:
#    #url: jdbc:mysql://192.168.0.16:3306/springboot_case_demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
#    #username: root
#    #password: 666666
#    #driver-class-name: com.mysql.cj.jdbc.Driver
#  shardingsphere:
#    datasource:
#      names: ds
#      ds:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://127.0.0.1:3306/springboot_case_demo
#        username: root
#        password: 666666
#    sharding:
#      tables:
#        blade_log_api_shardingjdbc:
#          actual-data-nodes: ds.blade_log_api_shardingjdbc_$->{2024..2025}_$->{1..12}
#          table-strategy:
#            standard:
#              sharding-column: create_time
#              precise-algorithm-class-name: com.springbootcasedemo.shardingjdpc.config.DatePreciseShardingAlgorithm
#              range-algorithm-class-name: com.springbootcasedemo.shardingjdpc.config.DatePreciseShardingAlgorithm
#      binding-tables:
#        - blade_log_api_shardingjdbc
#      defaultDataSourceName: ds
#    props:
#      sql:
#        show: true


#spring:
#  shardingsphere:
#    datasource:
#      names: ds
#    ds:
#      type: com.zaxxer.hikari.HikariDataSource
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://127.0.0.1:3306/springboot_case_demo
#      username: root
#      password: 666666
#    rules:
#      sharding:
#        tables:
#          blade_log_api_shardingjdbc:
#            key-generate-strategy:
#              column: id
#            database-strategy:
#              standard:
#                sharding-column: id
#                sharding-algorithm-name: database-inline
#        sharding-algorithms:
#          database-inline:
#            type: INLINE
#            props:
#              algorithm-expression: ds$->{id % 3}
#    props:
#      sql-show: show
spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yaml
#spring:
#  shardingsphere:
#    datasource:
#      names: ds0
#      ds0:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://127.0.0.1:3306/springboot_case_demo
#        username: root
#        password: 666666
#    rules:
#      sharding:
#        tables:
#          blade_log_api:
#            actual-data-nodes: ds0.blade_log_api_${2023..2024}${1..12} # 示例：202300-202311, 202400-202411
#            key-generate-strategy:
#              column: id
#            table-strategy:
#              standard:
#                sharding-column: create_time
#                sharding-algorithm-name: database-inline
#        sharding-algorithms:
#          database-inline:
#            type: INLINE
#            props:
#              algorithm-expression: blade_log_api_${create_time.toLocalDate().format(DateTimeFormatter.ofPattern('yyyyMM'))}
#    props:
#      sql-show: true


